// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerProductResponse handler product response
//
// swagger:model handler.productResponse
type HandlerProductResponse struct {

	// category id
	CategoryID int64 `json:"category_id,omitempty"`

	// category name
	CategoryName string `json:"category_name,omitempty"`

	// cost
	Cost float64 `json:"cost,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// stock code
	StockCode string `json:"stock_code,omitempty"`
}

// Validate validates this handler product response
func (m *HandlerProductResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler product response based on context it is used
func (m *HandlerProductResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerProductResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerProductResponse) UnmarshalBinary(b []byte) error {
	var res HandlerProductResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
