// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerResponse handler response
//
// swagger:model handler.response
type HandlerResponse struct {

	// message
	// Example: message
	Message string `json:"message,omitempty"`
}

// Validate validates this handler response
func (m *HandlerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler response based on context it is used
func (m *HandlerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerResponse) UnmarshalBinary(b []byte) error {
	var res HandlerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
