// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HandlerCreateProductRequest handler create product request
//
// swagger:model handler.createProductRequest
type HandlerCreateProductRequest struct {

	// category id
	// Required: true
	CategoryID *int64 `json:"category_id"`

	// cost
	// Required: true
	Cost *float64 `json:"cost"`

	// name
	// Required: true
	Name *string `json:"name"`

	// number
	// Required: true
	Number *int64 `json:"number"`

	// stock code
	// Required: true
	StockCode *string `json:"stock_code"`
}

// Validate validates this handler create product request
func (m *HandlerCreateProductRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStockCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HandlerCreateProductRequest) validateCategoryID(formats strfmt.Registry) error {

	if err := validate.Required("category_id", "body", m.CategoryID); err != nil {
		return err
	}

	return nil
}

func (m *HandlerCreateProductRequest) validateCost(formats strfmt.Registry) error {

	if err := validate.Required("cost", "body", m.Cost); err != nil {
		return err
	}

	return nil
}

func (m *HandlerCreateProductRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *HandlerCreateProductRequest) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("number", "body", m.Number); err != nil {
		return err
	}

	return nil
}

func (m *HandlerCreateProductRequest) validateStockCode(formats strfmt.Registry) error {

	if err := validate.Required("stock_code", "body", m.StockCode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this handler create product request based on context it is used
func (m *HandlerCreateProductRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerCreateProductRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerCreateProductRequest) UnmarshalBinary(b []byte) error {
	var res HandlerCreateProductRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
