// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlerAuthResponse handler auth response
//
// swagger:model handler.authResponse
type HandlerAuthResponse struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this handler auth response
func (m *HandlerAuthResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handler auth response based on context it is used
func (m *HandlerAuthResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlerAuthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlerAuthResponse) UnmarshalBinary(b []byte) error {
	var res HandlerAuthResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
