// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaginationPages pagination pages
//
// swagger:model pagination.Pages
type PaginationPages struct {

	// items
	Items interface{} `json:"items,omitempty"`

	// page
	Page int64 `json:"page,omitempty"`

	// page count
	PageCount int64 `json:"pageCount,omitempty"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`

	// total count
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this pagination pages
func (m *PaginationPages) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pagination pages based on context it is used
func (m *PaginationPages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaginationPages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaginationPages) UnmarshalBinary(b []byte) error {
	var res PaginationPages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
